### PR TITLE
Asserts types validator and extracor for tasks feature

### PR DESCRIPTION
**Pull request by solar05**

### CODE REVIEW

**Comment by vtm9** [comment]
why do we need this lib?
image

**Comment by solar05** [comment]
@vtm9 later, for asserts generation

**Comment by vtm9** [comment]
ohh, ok, but it's not maintained

**Comment by solar05** [comment]
@vtm9 main idea is that we takes task input signature and try to generate asserts, after generation we need validations to ensure that our asserts are corresponds input signature and output type
We need to think about what generators we want to make, as the primary implementation, take the library with the generation of fake data and just try to generate from a signature (with hashes will be a problem), and in the future, perhaps the user using dsl that we give him, will write similar generators, but this will have to live to see.

**Comment by solar05** [comment]
@vtm9 oh, missed that, will switch this library 👌

**Comment by vtm9** [comment]
awesome

**Pull request merged**
